#!/bin/bash

APPLICATION_DIR=$1
NCS_INSTALL_DIR=$2

if [ -z "$APPLICATION_DIR" ] || [ -z "$NCS_INSTALL_DIR" ]; then
    echo "Usage: build-env <application_dir> <ncs_install_dir>"
    return 1
fi

export NCS_INSTALL_DIR="$NCS_INSTALL_DIR"
export APPLICATION_DIR="$APPLICATION_DIR"

nrfutil sdk-manager toolchain launch --ncs-version=v3.0.2 -- bash -c "
    source \"$NCS_INSTALL_DIR/v3.0.2/zephyr/zephyr-env.sh\" &&
    export PS1=\"(bbb-led-dongle):\w\$ \" &&
    echo \"Environment initialized. Type exit or Ctrl-D to quit.\" &&
    exec bash --norc --noprofile -i
"